### ISSUE TITLE
Support for STM32

### ISSUE THREAD

**Issue by mklomp** [MrYsLab/FirmataExpress#7]
Hi,

Trying to move from pymata to pymata4 I run into an issue with the STM32F103C8 (black pill). In the old situation we got pymata working with FirmataPlusDue uploaded to the STM32. After uploading FirmataExpress to the SMT32 and running pymata4 I get the error "Firmata Sketch Firmware Version Not Found". I get the same error when I upload StandardFirmata. 

After uploading FirmataPlusDue again pymata4 is able to connect, but is not able to get callback working and I get no values. Although not sure whether this is a pymata4 or FirmataExpress issue, I suppose it is the latter. So on my STM32 I have:

StandardFirmata + pymata4 -> Error
FirmataExpress + pymata4 -> Error
FirmataPlusDue + pymata4 -> Connecting, but not working
FirmataPlusDue + pymata -> Working (but old versions we want to ditch)

Given that SMT32 is in Boards.h makes me believe it is supposed to work without a special Due version like FirmataPlus (as far as I can see the only difference between those two is some libraries that are not compatible with AMR/Due/STM32). 

Hope you can help.

**Comment by MrYsLab** [comment]
Let's try a simple experiment. If you load FirmataExpress and then [run this sketch](https://github.com/MrYsLab/pymata4/blob/master/examples/digital_output.py) (you will need to change the pin from 6 to 13) is the board found and does the board LED blink?

**Comment by mklomp** [comment]
I loaded FirmataExpress to the STM32:

```
Sketch uses 46496 bytes (70%) of program storage space. Maximum is 65536 bytes.
Global variables use 5100 bytes (24%) of dynamic memory, leaving 15380 bytes for local variables. Maximum is 20480 bytes.
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Opening DFU capable USB device...
ID 1eaf:0003
Run-time device DFU version 0110
Claiming USB DFU Interface...
Setting Alternate Setting MrYsLab/FirmataExpress#2 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0110
Device returned transfer size 1024
Copying data from PC to DFU device
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Download	[=========================] 100%        46808 bytes
Download done.
state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Done!
Resetting USB to switch back to runtime mode
Waiting for /dev/ttyACM0 serial..................... Done.
```

So, everything as expected there. And then ran:

```
$ python3 digital_output.py 
pymata4:  Version 1.8

Copyright (c) 2020 Alan Yorinks All Rights Reserved.

Opening all potential serial ports...
	/dev/ttyACM0

Waiting 4 seconds(arduino_wait) for Arduino devices to reset...

Searching for an Arduino configured with an arduino_instance = 1
Arduino compatible device found and connected to /dev/ttyACM0

Retrieving Arduino Firmware ID...
Traceback (most recent call last):
  File "digital_output.py", line 54, in <module>
    board = pymata4.Pymata4()
  File "/usr/local/lib/python3.7/dist-packages/pymata4/pymata4.py", line 275, in __init__
    raise RuntimeError(f'Firmata Sketch Firmware Version Not Found')
RuntimeError: Firmata Sketch Firmware Version Not Found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "digital_output.py", line 54, in <module>
    board = pymata4.Pymata4()
  File "/usr/local/lib/python3.7/dist-packages/pymata4/pymata4.py", line 275, in __init__
    raise RuntimeError(f'Firmata Sketch Firmware Version Not Found')
RuntimeError: Firmata Sketch Firmware Version Not Found
```

**Comment by MrYsLab** [comment]
The Firmata versions that FirmataExpress (2.5.8) and FirmataPlusDue (2.5.3) are based on are different. I am not sure if things were broken by 2.5.8 for your board or not. Since you mention that StandardFirmata does not work, then I assume something was introduced in 2.5.8 that is incompatible with your board.

I just ran FirmataPlus for the Uno with pymata4 and I am not having any issues - callbacks work correctly. 

If you would like to try this, you will need to set the baud_rate parameter to 57600 when instantiating  pymata4. 
```
board = pymata4.Pymata4(baud_rate=57600)

```
To run with StandardFirmata, you would start pymata4 the same way specifying the speed.

Please let me know if you test either FirmataPlusDue and/or StandardFirmata setting the baud rate, and if you are still having issues.

If FirmataPlusDue works, then that may be the only solution.

**Comment by mklomp** [comment]
Thanks, for some reason this made me rethink the issue and at least I got past this error. For completeness, I was uploading with the wrong setting (CDCgen instead of CDC). Unfortunately I do not get a blinking led, nor data from the STM yet. 

So now I have FirmataExpress on my STM32, but when I run the blink example: no blinking. And when I run the [analog_input example]([url](https://github.com/MrYsLab/pymata4/blob/master/examples/analog_input_with_time_stamps.py)) I do not seem to get any data:

```
pymata4:  Version 1.8

Copyright (c) 2020 Alan Yorinks All Rights Reserved.

Opening all potential serial ports...
	/dev/ttyACM0

Waiting 4 seconds(arduino_wait) for Arduino devices to reset...

Searching for an Arduino configured with an arduino_instance = 1
Arduino compatible device found and connected to /dev/ttyACM0

Retrieving Arduino Firmware ID...
Arduino Firmware ID: 1.1 FirmataExpress.ino

Retrieving analog map...
Auto-discovery complete. Found 35 Digital Pins and 10 Analog Pins


Reading latest analog input data for pin 0 = 0 change received on 1970-01-01 01:00:00 (raw_time: 0)
Reading latest analog input data for pin 0 = 0 change received on 1970-01-01 01:00:00 (raw_time: 0)
```
But when I run with the same FirmataExpress but using pymata it works:

```
$ python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> from PyMata.pymata import PyMata
>>> board = PyMata("/dev/ttyACM0", verbose=True, baud_rate=115200)

Python Version 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0]

PyMata version 2.20  Copyright(C) 2013-19 Alan Yorinks    All rights reserved.

Opening Arduino Serial port /dev/ttyACM0 

Please wait while Arduino is being detected. This can take up to 30 seconds ...
Board initialized in 0 seconds
Total Number of Pins Detected = 35
Total Number of Analog Pins Detected = 10
>>> board.set_pin_mode(0, board.INPUT, board.ANALOG)
>>> 
>>> while True:
...     print board.analog_read(0)
...     time.sleep(0.01)
... 
40
40
24
24
24
```

Also tested with StandardFirmata instead of FirmataExpress: Same behaviour (data with pymata, no data with pymata4). Also checked on the arduino nano that I had lying around: everything worked as expected. So this makes me believe that this is not a FirmataExpress but a pymata4 issue. Let me know if you agree and want me to open this as an issue for pymata4.
